pipeline {
  options { timestamps() }
  agent {
    dockerfile {
      label 'docker-slave'
      args '--device=/dev/kvm'
      dir 'jenkins/nfsroot/'
    }
  }

  stages {
    stage("Setup") {
      steps {
        script {
          env.PIPELINE_VERSION = VersionNumber(
             versionNumberString: '${BUILD_DATE_FORMATTED,"yyyyMMdd"}.${BUILDS_TODAY_Z}')
        }
        sh 'mkdir ${PIPELINE_VERSION}'
      }
    }

    stage("Build NFS images") {
      parallel {
        stage("Build NFS image for arm64") {
          steps {
              sh 'mkdir ${PIPELINE_VERSION}/arm64'
              sh 'debos -t architecture:arm64 -t basename:${PIPELINE_VERSION}/arm64/stretch jenkins/nfsroot/debos/stretch.yaml'
          }
        }

        stage("Build NFS image for armel") {
          steps {
              sh 'mkdir ${PIPELINE_VERSION}/armel'
              sh 'debos -t architecture:armhf -t basename:${PIPELINE_VERSION}/armel/stretch jenkins/nfsroot/debos/stretch.yaml'
          }
        }

        stage("Build NFS image for x86") {
          steps {
              sh 'mkdir ${PIPELINE_VERSION}/x86'
              sh 'debos -t architecture:i386 -t basename:${PIPELINE_VERSION}/x86/stretch jenkins/nfsroot/debos/stretch.yaml'
          }
        }

        stage("Build NFS image for x86_64") {
          steps {
              sh 'mkdir ${PIPELINE_VERSION}/x86_64'
              sh 'debos -t architecture:amd64 -t basename:${PIPELINE_VERSION}/x86_64/stretch jenkins/nfsroot/debos/stretch.yaml'
          }
        }
      }
    }

    stage ("Upload images") {
      environment {
        API = 'https://staging-api.kernelci.org'
        PUBLISH_PATH = 'images/rootfs/debian/${PIPELINE_VERSION}'
      }
      steps {
        sh 'python push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH}/arm64 --file ${PIPELINE_VERSION}/arm64/stretch-initramfs.gz ${PIPELINE_VERSION}/arm64/stretch-nfsroot.tar.gz'
        sh 'python push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH}/armel --file ${PIPELINE_VERSION}/armel/stretch-initramfs.gz ${PIPELINE_VERSION}/armel/stretch-nfsroot.tar.gz'
        sh 'python push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH}/x86 --file ${PIPELINE_VERSION}/x86/stretch-initramfs.gz ${PIPELINE_VERSION}/x86/stretch-nfsroot.tar.gz'
        sh 'python push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH}/x86_64 --file ${PIPELINE_VERSION}/x86_64/stretch-initramfs.gz ${PIPELINE_VERSION}/x86_64/stretch-nfsroot.tar.gz'
      }
    }
  }
}

